# # my global config
# global:
#   scrape_interval:     15s # By default, scrape targets every 15 seconds.
#   evaluation_interval: 15s # By default, scrape targets every 15 seconds.
#   # scrape_timeout is set to the global default (10s).

#   # Attach these labels to any time series or alerts when communicating with
#   # external systems (federation, remote storage, Alertmanager).
#   external_labels:
#       monitor: 'my-project'

# # Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - 'alert.rules'
#   # - "first.rules"
#   # - "second.rules"

# # alert
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

# # A scrape configuration containing exactly one endpoint to scrape:
# # Here it's Prometheus itself.
# scrape_configs:
#   # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

#   - job_name: app
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['host.docker.internal:8000']

#   - job_name: 'prometheus'

#     # Override the global default and scrape targets from this job every 5 seconds.
#     scrape_interval: 5s

#     static_configs:
#          - targets: ['localhost:9090']


#   - job_name: 'cadvisor'

#     # Override the global default and scrape targets from this job every 5 seconds.
#     scrape_interval: 5s

#     dns_sd_configs:
#     - names:
#       - 'tasks.cadvisor'
#       type: 'A'
#       port: 8080

# #     static_configs:
# #          - targets: ['cadvisor:8080']

#   - job_name: 'node-exporter'

#     # Override the global default and scrape targets from this job every 5 seconds.
#     scrape_interval: 5s

#     dns_sd_configs:
#     - names:
#       - 'tasks.node-exporter'
#       type: 'A'
#       port: 9100
#   - job_name: 'kube-state-metrics'
#     scrape_interval: 5s
#     honor_timestamps: true
#     metrics_path: /metrics
#     static_configs:
#       - targets: ['13.233.156.77:30466']
#     metric_relabel_configs:
#       - target_label: cluster
#         replacement: ITDK8sCluster 
# #  - job_name: 'pushgateway'
# #    scrape_interval: 10s
# #    dns_sd_configs:
# #    - names:
# #      - 'tasks.pushgateway'
# #      type: 'A'
# #      port: 9091

#      static_configs:
#         - targets: ['13.233.156.77:9100']







# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'my-project'

# Rule files
rule_files:
  - 'alert.rules'

# Alerting
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# Scrape configurations
scrape_configs:
  # Application scrape config
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']

  # Prometheus self-scraping
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # cAdvisor scrape config
  - job_name: 'cadvisor'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080

  # Node Exporter scrape config
  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100

  # Kube State Metrics scrape config
  - job_name: 'kube-state-metrics'
    scrape_interval: 5s
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
      - targets: ['13.233.156.77:30466']
    metric_relabel_configs:
      - target_label: cluster
        replacement: ITDK8sCluster
